"""Alembic environment.

The app passes its own connection in `config.attributes["connection"]` (see database/session.py).
From the CLI, a connection is opened from the app settings (DATABASE_URL / .env).
"""

import asyncio

from alembic import context
from sqlalchemy import pool
from sqlalchemy.engine import Connection
from sqlalchemy.ext.asyncio import create_async_engine

from ai_service.app import models  # noqa: F401  (registers tables on Base.metadata)
from ai_service.app.core.config import settings
from ai_service.app.database.session import Base

target_metadata = Base.metadata


def run_with(connection: Connection) -> None:
    # Batch mode lets autogenerated ALTERs work on SQLite, which cannot alter most column properties.
    context.configure(connection=connection, target_metadata=target_metadata, render_as_batch=True)
    with context.begin_transaction():
        context.run_migrations()


async def run_from_settings() -> None:
    engine = create_async_engine(settings.database_url, poolclass=pool.NullPool)
    async with engine.begin() as connection:
        await connection.run_sync(run_with)
    await engine.dispose()


if context.is_offline_mode():
    context.configure(url=settings.database_url, target_metadata=target_metadata, literal_binds=True)
    with context.begin_transaction():
        context.run_migrations()
elif (provided := context.config.attributes.get("connection")) is not None:
    run_with(provided)
else:
    asyncio.run(run_from_settings())
