"""Pin the AI service's runtime dependencies to the versions installed in the current environment.

    python scripts/lock_deps.py      # rewrite ai_service/constraints.txt

Walks ai_service/requirements.txt and every transitive requirement whose environment marker applies
here, then writes `name==version` lines. Use it as a pip constraints file:

    pip install -r ai_service/requirements.txt -c ai_service/constraints.txt

Packages only needed on another platform (e.g. uvloop on Linux) are not pinned; pip resolves them.
"""

import sys
from importlib import metadata
from pathlib import Path

from packaging.requirements import Requirement
from packaging.utils import canonicalize_name

ROOT = Path(__file__).resolve().parents[1]
REQUIREMENTS = ROOT / "ai_service" / "requirements.txt"
CONSTRAINTS = ROOT / "ai_service" / "constraints.txt"
HEADER = "# Generated by scripts/lock_deps.py from ai_service/requirements.txt. Do not edit by hand.\n"


def _top_level() -> list[Requirement]:
    lines = (line.split("#", 1)[0].strip() for line in REQUIREMENTS.read_text().splitlines())
    return [Requirement(line) for line in lines if line]


def resolve() -> dict[str, str]:
    pinned: dict[str, str] = {}
    queue: list[tuple[Requirement, str]] = [(req, "") for req in _top_level()]
    seen: set[tuple[str, str]] = set()
    while queue:
        req, extra = queue.pop()
        if req.marker is not None and not req.marker.evaluate({"extra": extra}):
            continue
        name = canonicalize_name(req.name)
        for wanted_extra in [""] + sorted(req.extras):
            if (name, wanted_extra) in seen:
                continue
            seen.add((name, wanted_extra))
            try:
                dist = metadata.distribution(req.name)
            except metadata.PackageNotFoundError:
                sys.exit(f"{req.name} is required but not installed; pip install -r {REQUIREMENTS} first")
            pinned[name] = dist.version
            queue += [(Requirement(r), wanted_extra) for r in dist.requires or []]
    return dict(sorted(pinned.items()))


def render(pinned: dict[str, str]) -> str:
    return HEADER + "".join(f"{name}=={version}\n" for name, version in pinned.items())


def main() -> None:
    content = render(resolve())
    CONSTRAINTS.write_text(content, newline="\n")
    print(f"Wrote {len(content.splitlines()) - 1} pins to {CONSTRAINTS.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
